### ISSUE TITLE
Interfering with theme

### ISSUE THREAD

**Issue by point-4ward** [eyedeekay/I2P-in-Private-Browsing-Mode-Firefox#105]
Hi.

Only a minor issue (I think!), but I use a dark theme for my firefox.  With this i2p addon enabled it themes i2p windows to dark blue (which I presume is desired behaviour), but it defaults other 'normal' windows back to the default firefox theme rather than the theme I had set.

The behaviour I see is that when I very first start firefox my selected black theme is in place for a few seconds, then as soon as the i2p addon starts the theme reverts back to the 'default' light theme that firefox comes with when you first install it.  It's actually slightly weirder than that because I have completely disabled the default firefox theme, but it still seems to fallback to it when the i2p addon is loaded.  Then opening i2p pages turns the theme blue, then dropping back to clearweb pages reverts to the default light theme.

Disabling the i2p addon restores my dark theme immediately.  Re-enabling the addon immediately drops back to default.

Of course, I would like to have my dark theme for clearweb, and the blue for i2p.

The only other issue I found that mentiond this was:  https://github.com/eyedeekay/I2P-in-Private-Browsing-Mode-Firefox/issues/38

That issue was closed as fixed.

Thanks for looking.

**Comment by eyedeekay** [comment]
Shoot. It must still be buggy. Thanks for the report, I'll have the issue fixed in the next version.

**Comment by eyedeekay** [comment]
98% fixed in: https://i2pgit.org/idk/I2P-in-Private-Browsing-Mode-Firefox/-/merge_requests/20

Cutting a new release sometime next week.

**Comment by mf-social** [comment]
Ace, will try and test it out as soon as it's released 👍

**Comment by Midou36O** [comment]
It still happens to me, firefox goes to the default theme for normal tabs when i2p changes it :P

**Comment by eyedeekay** [comment]
Upstream bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1415267
Forum post: https://discourse.mozilla.org/t/is-there-a-known-workaround-for-undefined-behavior-in-theme-reset/88488
Until I can figure out a workaround or Mozilla fixes the bug it will switch to the default theme when you leave an I2P tab.

**Comment by eyedeekay** [comment]
Leaving this open because what I've done to fix it is really very clunky. It must be if this is not acceptable behavior for `theme.reset` but I **think** it's good enough, as a workaround, for now.

**Comment by eyedeekay** [comment]
Damn. That's what I was afraid of, it's only half a fix. The theme survives the rest of the browsing session, but it doesn't get applied in the right order when browsing is restarted. I'll need to work on it some more.

**Comment by BrenBarn** [comment]
This behavior is extraordinarily hostile to users.  I installed the extension and it screwed up the look of my browser.  I uninstalled it, and the screwups remain.  Can you provide information about exactly which browser settings this extension modifiers, so I can reset them and get the previous browser look and feel back?
